RESULT_CLAIM_PATTERNS = [
    r"\byields?\b.*\b(gain|improvement|higher|better|substantial|significant)",
    r"\bachieves?\b.*\b(state-of-the-art|best|higher|better)",
    r"\boutperforms?\b",
    r"\bresults?\s+(show|indicate|demonstrate)",
]

LIMITATION_OR_UNKNOWN_PATTERNS = [
    r"\bnot\s+(specified|provided|described|included|available|clear)\b",
    r"\bunclear\b",
    r"\bunknown\b",
    r"\bmay\s+need\b",
    r"\bmay\s+differ\b",
    r"\brequires?\s+manual\b",
    r"\bnot\s+fully\b",
    r"\bno\s+(ablation|analysis|statistical|significance)\b",
    r"\bfuture\s+work\b",
    r"\bfallback\s+plan\b",
    r"\blimitation\b",
]

SECRET_OR_ENV_PATTERNS = [
    r"\bapi[_\s-]*key\b",
    r"\bsecret\b",
    r"\bcredential\b",
    r"\bbearer\b",
    r"\borganization\s+id\b",
    r"\bopenrouter\s+api\s+key\b",
    r"\banthropic_api_key\b",
    r"\bopenai_api_key\b",
    r"\bsecrets\s+file\b",
    r"\blocal\s+path\b",
    r"\bslurm\b",
    r"\ba100\b",
    r"\bgpu\b",
    r"\bcuda\b",
    r"\bfirebase\b",
    r"\brate\s+limit\b",
]

ORDINARY_SCALAR_PATTERNS = [
    r"\brandom\s+seed\b",
    r"\bseed\s*[:=]\s*\d+",
    r"\blearning\s+rate\b",
    r"\blr\s*=\s*[0-9.e-]+",
    r"\bbatch\s+size\b",
    r"\bweight\s+decay\b",
    r"\boptimizer\s+defaults\b",
    r"\bepoch(s)?\b",
    r"\bmax[_\s-]*tokens\b",
    r"\btemperature\b",
    r"\btop[_\s-]*p\b",
    r"\btop[_\s-]*k\b",
    r"\btimeout\b",
    r"\bretry\b",
    r"\bconcurrency\b",
    r"\brate\s+limit\b",
]

METHOD_CORE_KEYWORDS = [
    "stage",
    "prompt",
    "formula",
    "aggregation",
    "pooling",
    "embedding",
    "logit",
    "loss",
    "objective",
    "routing",
    "threshold",
    "calibration",
    "sampling",
    "split",
    "metric",
    "evaluation",
    "dataset",
    "preprocess",
    "token",
    "classification",
    "prediction",
    "confidence",
    "input",
    "output",
    "weight",
    "architecture",
    "module",
    "matrix",
    "json",
    "parse",
    "iteration",
    "inference",
    "training",
    "optimizer",
    "chain",
    "pipeline",
    "stage order",
    "decision rule",
]

EVALUATION_TERMS = [
    "metric",
    "evaluation",
    "evaluate",
    "accuracy",
    "auc",
    "ece",
    "expected calibration error",
    "rouge",
    "bleu",
    "judge",
    "f1",
    "perplexity",
    "entropy",
    "kl divergence",
    "baseline",
]

DATA_TERMS = [
    "dataset",
    "split",
    "sampling",
    "sample",
    "preprocess",
    "filter",
    "label",
    "data",
    "validation",
    "test set",
    "train set",
    "hugging face",
    "mc1_targets",
]

ARCHITECTURE_TERMS = [
    "embedding",
    "layer",
    "hidden",
    "matrix",
    "token",
    "logit",
    "architecture",
    "module",
    "frozen",
    "pretrained",
    "pooling",
    "normalization",
    "dimension",
]
